#!/bin/bash

# stops processing in case of failure
set -euo pipefail

# prints each line executed
set -x

pwd

echo "Your solution goes here"
echo "Testing push access"

# Internet connectvity issue was due to a firewall. First checked iptables
# but there didn't seem any rules for filtering there. Then by checking sytemctl
# services, saw that nftables.service was active and stopped the process.

echo "Fixing internet connectivity problem"
sudo systemctl stop nftables.service

# REF : http://manpages.ubuntu.com/manpages/xenial/en/man8/ufw.8.html
# We need a firewall to only allow grader.dtf.netsec.inf.ethz.ch to access
# the database server. For this, I thought of installing a convenient package 
# called ufw, which is easier and cleaner to use than iptables.

sudo apt-get install ufw -y

# To add a rule, we need the IP address of the server. For this I used, 
# sudo dig grader.dtf.netsec.inf.ethz.ch which returned 129.132.121.162

echo "Fixing database server access problem"

echo "y" | sudo ufw enable
sudo ufw allow ssh
sudo ufw allow proto tcp from 129.132.121.162 to any port 5432

# There is an Off-by-slash misconfiguration in the nginx server. After checking the log 
# files in /var/log/nginx/access.log, this was confirmed. To fix this, the location /app
# in /etc/nginx/sites-enabled/company-app needs to be changed to /app/

echo "Fixing the pwned issue"

sudo sed -i 's+location /app+location /app/+' /etc/nginx/sites-enabled/company-app.conf
